### PR TITLE
Added JS Calculator

### PR DESCRIPTION
**Pull request by B1TSH3LL**

### CODE REVIEW

**Review by Open-Source-you — CHANGES_REQUESTED** [review]
You need to merge all calculators into one website

**Comment by B1TSH3LL** [comment]
which website ??? i didnt get it

**Comment by B1TSH3LL** [comment]
you can just href to the folder it will be easy to link for your website'

**Comment by B1TSH3LL** [comment]
> You need to merge all calculators into one website

can you tell me which website you are talking about because there are many folders in the repo so ?

**Comment by B1TSH3LL** [comment]
Bruh ???

**Pull request closed without merging**
