### PR TITLE
Full_shooter_game

### PR DESCRIPTION
**Pull request by kishan779**

### CODE REVIEW

**Review by Open-Source-you — COMMENTED** [review]
please send game working link,then i merge your pr

**Comment by kishan779** [comment]
https://kishan779.github.io/Full_shooter_game/

**Comment by Open-Source-you** [comment]
> https://kishan779.github.io/Full_shooter_game/

game is not working properly

**Comment by kishan779** [comment]
https://kishan779.github.io/shooting_game/

**Pull request merged**
