### PR TITLE
some modification in CSS in calculator

### PR DESCRIPTION
**Pull request by lusifer65**
add hover effect and modification in CSS code and Html

### CODE REVIEW

**Comment by Open-Source-you** [comment]
> add hover effect and modification in CSS code and Html

send ss

**Comment by lusifer65** [comment]
ok

**Comment by lusifer65** [comment]
display focus->
image
 
button hover->
image

**Comment by lusifer65** [comment]
please check

**Comment by lusifer65** [comment]
👍

**Comment by lusifer65** [comment]
can i make something new like basic project

**Comment by lusifer65** [comment]
@Open-Source-you  can i add some new mini project

**Pull request merged**
